Autonomous Generation of Process Flow and Instrumentation Diagrams Using a Small Foundational Model
Introduction and Motivation
Chemical process design heavily relies on Process Flow Diagrams (PFDs) and Piping and Instrumentation Diagrams (PIDs), which are essential for visualizing industrial workflows, ensuring operational safety, and complying with regulatory standards. However, as chemical processes become more complex, manually designing these diagrams becomes increasingly time-consuming and prone to human error. The transition toward automation and digitalization in industrial operations necessitates intelligent systems capable of streamlining diagram generation while maintaining accuracy and consistency.

To address these challenges, we present an AI-driven framework that employs a small foundational model (LLaMA 3.2 1B) trained on chemical engineering data to automate the generation of PFDs, PIDs, and synthetic process pipelines. Our approach significantly reduces manual workload, enhances process design accuracy, and facilitates faster decision-making. By leveraging the capabilities of large-scale LLMs to generate synthetic datasets tailored to chemical engineering tasks, we fine-tune this specialized model to perform these tasks efficiently.

Methodology
The core of our approach involves a multi-stage framework designed to generate high-quality process diagrams with minimal expert intervention. First, we use large LLMs to create a synthetic dataset containing process pipelines, PFDs, and PIDs for 1,005 chemicals. This dataset is then used to fine-tune LLaMA 3.2 1B, equipping it with domain-specific knowledge to automate process diagram generation. Additionally, a diverse set of question-answer pairs covering fundamental chemical engineering concepts is generated to enhance the model’s logical reasoning and decision-making capabilities.

To further refine the model’s output, we implement Direct Preference Optimization (DPO) and Reinforcement Learning with Human Feedback (RLHF). These techniques allow the model to iteratively improve its responses by selecting preferred answers based on expert feedback. We also introduce Retrieval-Augmented Generation (RAG) to improve contextual understanding and information retrieval. Our RAG implementation operates at two levels: local RAG, which processes and retrieves information from individual documents, and global RAG, which consolidates data from multiple sources to provide a more comprehensive knowledge base.

To structure and organize chemical process knowledge, we employ ontological knowledge graphs built using Neo4j. These graphs enable the model to infer relationships between chemical compounds, process parameters, and instrumentation components, ensuring greater accuracy in diagram generation. Our framework is designed as a multi-agent system, where a meta-agent orchestrates various specialized agents, including a critique agent that evaluates the quality of generated diagrams and a reward model that refines outputs based on learned preferences. Human feedback is integrated into this system to provide continuous learning and adaptation.

Validation and Benchmarking
We conducted extensive evaluations to measure the effectiveness of our framework. A benchmark dataset of 1,500 test questions was created to assess model performance on known chemicals. Additionally, to evaluate generalization to unseen chemical processes, we tested the model on an extra set of 50 chemicals. We compared LLaMA 3.2 1B against a large general-purpose LLM using NVIDIA Nemotron reward model, evaluating helpfulness, correctness, coherence, complexity, and verbosity. The results demonstrated that our small foundational model performed comparably to the large LLM while being computationally more efficient. Furthermore, its ability to handle counter-questions and optimize responses through preference learning resulted in enhanced reasoning and contextual accuracy.

To validate real-world applicability, we performed first-principle verification of selected PFDs using DWSIM, an open-source process simulation tool. This ensured that the generated process diagrams aligned with thermodynamic and mass balance principles, further confirming the reliability of our approach. The integration of knowledge graphs and retrieval mechanisms improved contextual retrieval accuracy, making our system highly suitable for industrial applications.

Impact and Future Directions
This work represents a significant step toward automating process diagram generation using a small foundational model tailored for chemical engineering tasks. By reducing manual effort and improving design accuracy, our framework enhances the efficiency of process engineering workflows. The combination of multi-agent coordination, reinforcement learning, and retrieval-augmented generation ensures adaptability across various industrial scenarios. Our findings highlight that small, domain-focused models can achieve performance levels comparable to large LLMs while being more efficient and practical for specialized applications.

Future research will focus on expanding the model’s capabilities, particularly in real-time process simulation and dynamic validation of generated diagrams. We also aim to integrate the framework with industry-standard tools such as Aspen Plus, further improving its utility. By advancing AI-driven automation in chemical process design, this work lays the foundation for more scalable, efficient, and regulation-compliant solutions for industrial applications.
